### ISSUE TITLE
Admin menu items all pointing to same page

### ISSUE THREAD

**Issue by eiannone** [sulu-io/sulu-standard#472]
On my web server (IIS 7.5) I cannot use admin panel because all side menu items open the same page "People". After some investigation, I think the cause lies in an incorrect generation for menu items id values. I noticed that all menu items have the same id, as you can see in the attached screenshot:

![sulu-admin-navigation-error](https://cloud.githubusercontent.com/assets/439065/8455381/76482020-2004-11e5-9208-e4fadccee447.png)

I think that this is because id values are generated too fast, maybe within one microsecond, and the generation function, uniqid(), produces the same value, being based on microtime() as seed.

I'm proposing a different function for generating id values. Please see my PR https://github.com/sulu-io/SuluAdminBundle/pull/185
I can confirm that in my case it solves the problem.

**Comment by danrot** [comment]
Thank you for reporting this.

This is basically the same issue as https://github.com/sulu-io/sulu/issues/1190, and there is already a PR for that: https://github.com/sulu-io/sulu/pull/1191

I am just going to merge this one, so that it will also work correctly on windows. But in the long run i would suggest to remove the `uniqid` call, and generate speaking unique ids, something like `nav-item-contacts`, `nav-item-categories` and so on.
