### ISSUE TITLE
Apache Vhost SetEnv SYMFONY_ENV is being overwritten in htaccess 

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu-standard#574]
When I set the ENV in my apache vhost it will be overwritten by the htaccess (
https://github.com/sulu-io/sulu-standard/blob/develop/web/.htaccess#L8)

Vhost:

```
<VirtualHost *:80>
    DocumentRoot "/Users/alexanderschranz/Development/Sulu/sulu.lo/web"
    ServerName stage.sulu.lo
    <Directory "/Users/alexanderschranz/Development/Sulu/sulu.lo/web">
        Options Indexes FollowSymlinks
        SetEnv SYMFONY_ENV stage
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```

So currently the default ENV is on Apache dev and on Nginx prod.

https://github.com/sulu-io/sulu-standard/blob/develop/web/website.php#L8

I would say we should delete the SetEnv from the htaccess and set the default ENV in website.php and admin.php so it is on all webservers the same.

**Comment by danrot** [comment]
Sounds good to me. It would be nice if the `SYMFONY_ENV` environment variable could also be set on a OS level (using `export SYMFONY_ENV=dev`), so that a developer could easily set this as an default. But I am not sure if this also works for websites, or it is only taken into account for console commands.
